#!/bin/sh

cd $HOME/.wallpapers/zt_meteor/images/

main() {
    i=1

    while [[ ${i} -le 177 ]]; do
        feh --bg-scale $(ls -1 | grep ${i}.png | awk 'NR==1{print $1}')
        #sleep 0.01
        let i=i+1
    done

    i=1
}
 
while [[ 0 = 0 ]]; do
    main
done &
